-- 방명록 테이블 생성
CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  username TEXT NOT NULL,
  avatar_url TEXT,
  content TEXT NOT NULL,
  likes INTEGER DEFAULT 0 NOT NULL
);

-- 실시간 업데이트 활성화 (Supabase Realtime)
ALTER PUBLICATION supabase_realtime ADD TABLE posts;

-- 샘플 데이터 삽입
INSERT INTO posts (username, avatar_url, content, likes, created_at)
VALUES 
  ('홍길동', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix', '안녕하세요! 새로운 프로젝트 시작해서 너무 기대돼요 🚀', 12, '2025-05-20 10:00:00+09'),
  ('김민지', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aneka', '오늘 수업도 정말 재미있었어요! 다음 프로젝트도 기대할게요 😊', 8, '2025-05-20 11:30:00+09'),
  ('이서준', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Caleb', '새로운 프로젝트 성공적이에요! 선생님 감사합니다 🙌', 15, '2025-05-19 15:45:00+09');

-- 대댓글 테이블 생성
CREATE TABLE replies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  username TEXT NOT NULL,
  avatar_url TEXT,
  content TEXT NOT NULL
);

-- 대댓글 실시간 업데이트 활성화
ALTER PUBLICATION supabase_realtime ADD TABLE replies;
